### PR TITLE
[FIX] button toggle elm, search input elm, script logic cleared

### LINKED ISSUE #36: [Bug]: Search functionality not working
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Current Behavior

The search functionality is not working on the deployed web app.

### Expected Behavior

It should work and users should be able to search for opportunities.

### To Reproduce

Go to the deployed web app.
Search for anything
See the bug

### Anything else?

_No response_

### Hacktoberfest

- [X] Yeah

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by alkhimch**
@ashutoshkrris please review pull request. I suggest develop you,  one component has only one script tag. The main bug is .vue components has 2 script. When building process can't identify,  which is the components script.
Attempts to fix: #36

### CODE REVIEW

File: src/components/Header/Header.vue [hunk 1]
```diff
@@ -51,9 +46,10 @@ import GitHubSVG from "../../assets/githubsvg.svg";
 </template>
 
 <script>
+import GitHubSVG from '../../assets/GitHubSVG.svg';
```
Comment (ashutoshkrris) [inline src/components/Header/Header.vue]: This line should be:
```js
import GitHubSVG from '../../assets/githubsvg.svg';
```

**Review by ashutoshkrris — CHANGES_REQUESTED** [review]
